import { GiftCardProduct } from './types'

// TODO: Replace with Reloadly product catalog API
// Endpoint: GET https://giftcards.reloadly.com/countries/{countryCode}/products
// Auth: Bearer token from OAuth 2.0 flow

export const MOCK_GIFT_CARDS: GiftCardProduct[] = [
  {
    id: 'amazon-us',
    slug: 'amazon',
    brandName: 'Amazon',
    category: 'Shopping',
    logoUrl: '/brand-logos/amazon.svg',
    countryCodes: ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 10, label: '$10' },
      { value: 25, label: '$25' },
      { value: 50, label: '$50' },
      { value: 100, label: '$100' },
      { value: 200, label: '$200' },
    ],
    currency: 'USD',
    supportsCustomMessage: true,
    redemptionInstructions: 'Enter the gift card code at checkout on Amazon.com',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'spotify-us',
    slug: 'spotify',
    brandName: 'Spotify',
    category: 'Entertainment',
    logoUrl: '/brand-logos/spotify.svg',
    countryCodes: ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT', 'BR', 'MX'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 10, label: '$10' },
      { value: 30, label: '$30' },
      { value: 60, label: '$60' },
    ],
    currency: 'USD',
    supportsCustomMessage: true,
    redemptionInstructions: 'Redeem at spotify.com/redeem',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'starbucks-us',
    slug: 'starbucks',
    brandName: 'Starbucks',
    category: 'Food & Drink',
    logoUrl: '/brand-logos/starbucks.svg',
    countryCodes: ['US', 'CA', 'GB'],
    denominationType: 'RANGE',
    denominationRange: {
      min: 5,
      max: 500,
      step: 5,
    },
    currency: 'USD',
    supportsCustomMessage: true,
    redemptionInstructions: 'Present the gift card code in-store or add to Starbucks app',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'netflix-us',
    slug: 'netflix',
    brandName: 'Netflix',
    category: 'Entertainment',
    logoUrl: '/brand-logos/netflix.svg',
    countryCodes: ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT', 'BR', 'MX'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 25, label: '$25' },
      { value: 50, label: '$50' },
      { value: 100, label: '$100' },
    ],
    currency: 'USD',
    supportsCustomMessage: false,
    redemptionInstructions: 'Redeem at netflix.com/redeem',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'target-us',
    slug: 'target',
    brandName: 'Target',
    category: 'Shopping',
    logoUrl: '/brand-logos/target.svg',
    countryCodes: ['US'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 10, label: '$10' },
      { value: 25, label: '$25' },
      { value: 50, label: '$50' },
      { value: 100, label: '$100' },
    ],
    currency: 'USD',
    supportsCustomMessage: true,
    redemptionInstructions: 'Use in-store or online at target.com',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'uber-us',
    slug: 'uber',
    brandName: 'Uber',
    category: 'Travel',
    logoUrl: '/brand-logos/uber.svg',
    countryCodes: ['US', 'GB', 'CA', 'AU', 'BR', 'MX'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 25, label: '$25' },
      { value: 50, label: '$50' },
      { value: 75, label: '$75' },
      { value: 100, label: '$100' },
    ],
    currency: 'USD',
    supportsCustomMessage: false,
    redemptionInstructions: 'Add to Uber account in the app',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'steam-us',
    slug: 'steam',
    brandName: 'Steam',
    category: 'Gaming',
    logoUrl: '/brand-logos/steam.svg',
    countryCodes: ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT'],
    denominationType: 'FIXED',
    fixedDenominations: [
      { value: 10, label: '$10' },
      { value: 20, label: '$20' },
      { value: 50, label: '$50' },
      { value: 100, label: '$100' },
    ],
    currency: 'USD',
    supportsCustomMessage: false,
    redemptionInstructions: 'Redeem in Steam wallet',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
  {
    id: 'walmart-us',
    slug: 'walmart',
    brandName: 'Walmart',
    category: 'Shopping',
    logoUrl: '/brand-logos/walmart.svg',
    countryCodes: ['US'],
    denominationType: 'RANGE',
    denominationRange: {
      min: 10,
      max: 500,
      step: 10,
    },
    currency: 'USD',
    supportsCustomMessage: true,
    redemptionInstructions: 'Use in-store or online at walmart.com',
    isDigital: true,
    estimatedDeliveryMinutes: 5,
  },
]

export const CATEGORIES = [
  'All',
  'Shopping',
  'Entertainment',
  'Food & Drink',
  'Gaming',
  'Travel',
]
